export default localized = {
  en: {
    email: 'Email',
    emailPlaceholder: 'Enter your email address',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    login: 'Log In',
    passwordForgot: 'Forgot your password?',
    signUp: 'Sign up for an account',

    apple: 'Sign in with Apple',
    facebook: 'Login with Facebook',
    google: 'Login with Google',
    fullName: 'Full name',
    displayName: 'Display name',
    age: 'How old are you?',
    bio: 'Tell me something about you...',
    camera: 'Camera',
    folder: 'Photo Library',
    greetings: user => `${user}, just one more thing...`,
    instruction: 'Please select the topics that best suits you:',
  },
  pt: {
    email: 'Email',
    emailPlaceholder: 'Seu endereço de email',
    password: 'Senha',
    passwordPlaceholder: 'Senha de acesso',
    login: 'Entrar',
    passwordForgot: 'Esqueceu sua senha?',
    signUp: 'Criar uma conta',
    apple: 'Entrar com Apple',
    facebook: 'Login com Facebook',
    google: 'Login com Google',
    newUser: 'Cadastrar',
    fullName: 'Nome Completo',
    displayName: 'Nome de exibição',
    age: 'Quantos anos você tem?',
    bio: 'Me conte algo sobre você...',
    camera: 'Câmera',
    folder: 'Biblioteca de Fotos',
    greetings: user => `${user}, so mais uma coisa...`,
    instruction: 'Por favor selecione os topicos que mais o agrada:',
  },
};
