export default localized = {
  en: {
    app_name: 'ManChat',
    slogan: 'No man is an island',
    apple: 'Sign in with Apple',
    facebook: 'Login with Facebook',
    google: 'Login with Google',
    signUp: 'Sign Up',
    fullName: 'Full name',
    displayName: 'Display name',
    age: 'How old are you?',
    bio: 'Tell me something about you...',
    camera: 'Camera',
    folder: 'Photo Library',
    greetings: user => `${user}, just one more thing...`,
    instruction: 'Please select the topics that best suits you:',
  },
  pt: {
    app_name: 'ManChat',
    slogan: 'Nenhum homem é uma ilha',
    apple: 'Entrar com Apple',
    facebook: 'Login com Facebook',
    google: 'Login com Google',
    newUser: 'Cadastrar',
    fullName: 'Nome Completo',
    displayName: 'Nome de exibição',
    age: 'Quantos anos você tem?',
    bio: 'Me conte algo sobre você...',
    camera: 'Câmera',
    folder: 'Biblioteca de Fotos',
    greetings: user => `${user}, so mais uma coisa...`,
    instruction: 'Por favor selecione os topicos que mais o agrada:',
  },
};
